"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "allow-fetch-tags"
description = "Enables the fetch_tags command without any pre-configured scope."
commands.allow = ["fetch_tags"]

[[permission]]
identifier = "deny-fetch-tags"
description = "Denies the fetch_tags command without any pre-configured scope."
commands.deny = ["fetch_tags"]
