"$schema" = "../../schemas/schema.json"

[[permission]]
identifier = "allow-updater-check-now"
description = "Enables the updater_check_now command without any pre-configured scope."
commands.allow = ["updater_check_now"]

[[permission]]
identifier = "deny-updater-check-now"
description = "Denies the updater_check_now command without any pre-configured scope."
commands.deny = ["updater_check_now"]
